# Generated by Django 2.2.16 on 2020-09-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recipe_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
